version: '3'

#
#######################################
# Folder structure
#######################################
#
# (1) This boilerplate assumes that `index.php` is stored inside `htdocs`.
#
# However, for a more secure setup, the following is recommended:
# (2) In addition to (1), `assets`, `index.php` & `.htaccess` are
# stored inside `public`.
#
# See https://getkirby.com/docs/guide/configuration#custom-folder-setup
#

services:
  php:
    build:
      context: htdocs
      dockerfile: docker/php.dockerfile
      args:                     # 👈 move args here under build
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    volumes:
      - sock:/sock
      # (1)
      - ./htdocs:/app
      # (2)
      # - ./htdocs/public:/app/public
      # - ./htdocs/site:/app/site
      # - ./htdocs/storage:/app/storage
      # - ./htdocs/vendor:/app/vendor
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - no_proxy=${no_proxy}
      - NO_PROXY=${NO_PROXY}
    networks:
      - php-net


  nginx:
    build:
      context: htdocs
      dockerfile: docker/nginx.dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - no_proxy=${no_proxy}
      - NO_PROXY=${NO_PROXY}      
    ports:
      - 80:80
    volumes:
      - sock:/sock
      # (1)
      - ./htdocs:/app
      # (2)
      # - ./htdocs/public:/app/public:ro
    depends_on:
      - php
    networks:
      - php-net

volumes:
  sock:
    driver: local

networks:
  php-net:
    driver: bridge
